Update cassandra.yml

diff --git a/.github/workflows/cassandra.yml b/.github/workflows/cassandra.yml
--- a/.github/workflows/cassandra.yml
+++ b/.github/workflows/cassandra.yml
@@ -57,18 +57,20 @@ jobs:
             echo "Waiting for keyspace 'company'..."
             sleep 5
           done
+      - name: List all CQL files
+        run: ls -l *.cql
 
-      - name: Apply other CQL scripts
+      - name: Apply all CQL scripts
         run: |
           for file in $(find . -name '*.cql' | grep -v 'company.cql'); do
             echo "Applying $file..."
-            docker cp "$file" cassandra_test :/"$(basename $file)"
-            docker exec cassandra_test  cqlsh -f "/$(basename $file)" || (echo "Failed to apply $file!" && exit 1)
+            container_id=$(docker ps -q -f name=cassandra_test)
+            if [[ -z "$container_id" ]]; then
+              echo "Error: Cassandra container not found!" && exit 1
+            fi
+            docker cp "$file" "$container_id":/"$(basename $file)"
+            docker exec "$container_id" cqlsh -f "/$(basename $file)" || (echo "Failed to apply $file!" && exit 1)
           done
-
-
-      - name: List all CQL files
-        run: ls -l *.cql
       
       - name: List keyspaces after execution
         run: docker exec cassandra_test  cqlsh -e "DESCRIBE KEYSPACES"
