Update cassandra.yml

diff --git a/.github/workflows/cassandra.yml b/.github/workflows/cassandra.yml
--- a/.github/workflows/cassandra.yml
+++ b/.github/workflows/cassandra.yml
@@ -47,16 +47,13 @@ jobs:
           done
       - name: Wait for keyspace creation
         run: sleep 5
-
-      - name: Verify keyspace and table
+      - name: List all CQL files
+        run: ls -l *.cql
+      - name: Show company.cql content inside container
+        run: docker exec $(docker ps -q -f ancestor=cassandra:4.0) cat /company.cql
+      - name: Apply company.cql separately
         run: |
-          echo "Checking if keyspace 'company' exists..."
-          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES" | grep -q company || (echo "Keyspace 'company' not found!" && exit 1)
-          
-          echo "Checking if table 'employees' exists..."
-          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE TABLES IN company" | grep -q employees || (echo "Table 'employees' not found!" && exit 1)
-
-
+          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -f /company.cql || (echo "Failed to apply company.cql!" && exit 1)
 
      
       - name: Install dependencies
@@ -66,6 +63,15 @@ jobs:
         #run: |
           #docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "INSERT INTO test_keyspace.users (id, name) VALUES (1, 'Ekaterina');"
 
+      #- name: Verify keyspace and table
+       # run: |
+        #  echo "Checking if keyspace 'company' exists..."
+        #  docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES" | grep -q company || (echo "Keyspace 'company' not found!" && exit 1)
+          
+         # echo "Checking if table 'employees' exists..."
+          #docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE TABLES IN company" | grep -q employees || (echo "Table 'employees' not found!" && exit 1)
+
+      
       - name: Fetch data from Cassandra
         run: |
           docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "SELECT * FROM test_keyspace.users;"
