do cql all files cassandra.yml

diff --git a/.github/workflows/cassandra.yml b/.github/workflows/cassandra.yml
--- a/.github/workflows/cassandra.yml
+++ b/.github/workflows/cassandra.yml
@@ -47,6 +47,13 @@ jobs:
           docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -f /schema.cql || (echo "Schema failed to apply!" && exit 1)
           echo "Schema applied successfully!"
           sleep 5
+      - name: Apply all CQL scripts
+        run: |
+          for file in $(find . -name '*.cql'); do
+            echo "Applying $file..."
+            docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -f "$file" || (echo "Failed to apply $file!" && exit 1)
+          done
+
 
       - name: Check if keyspace exists
         run: docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES"
@@ -54,9 +61,9 @@ jobs:
       - name: Install dependencies
         run: pip install -r requirements.txt
 
-      - name: Insert test data
-        run: |
-          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "INSERT INTO test_keyspace.users (id, name) VALUES (1, 'Ekaterina');"
+      #- name: Insert test data
+        #run: |
+          #docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "INSERT INTO test_keyspace.users (id, name) VALUES (1, 'Ekaterina');"
 
       - name: Fetch data from Cassandra
         run: |
